# Generated by Django 5.1.5 on 2025-02-09 15:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('standard', 'Стандартный'), ('non_standard', 'Нестандартный')], default='standard', max_length=15)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=200, verbose_name='Название платформы')),
                ('platform_code', models.CharField(max_length=5, verbose_name='Код платформы')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('mail', models.CharField(max_length=50, verbose_name='Email')),
                ('number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('company', models.CharField(max_length=50, verbose_name='Наименование организации')),
                ('privacy_file', models.FileField(blank=True, null=True, upload_to='uploads/privacy_file/', verbose_name='Файл конфиденциальности')),
                ('processing_data', models.BooleanField(verbose_name='Я согласен на обработку персональных данных')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Substrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness_type', models.CharField(choices=[('standard', 'Стандартная толщина подложки'), ('non_standard', 'Нестандартная толщина подложки')], default='standard', max_length=15, verbose_name='Тип подложки')),
            ],
        ),
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('standard', 'Стандартная'), ('non_standard', 'Нестандартная')], default='standard', max_length=15)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='topic_files/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='account.message')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('company_name', models.CharField(max_length=200, verbose_name='Наименование компании заказчика')),
                ('is_nda_signed', models.BooleanField(default=False, verbose_name='NDA подписано?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.role')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.CreateModel(
            name='TechnicalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_process', models.CharField(max_length=50, verbose_name='Название технического процесса')),
                ('PDK_file', models.FileField(blank=True, default='', upload_to='uploads/PDK/%Y/%m/%d/', verbose_name='Файл КИП')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=14)),
                ('customer_product_name', models.CharField(help_text='Пояснение для имени запуска', max_length=200, verbose_name='Имя запуска')),
                ('order_start', models.CharField(choices=[('NEW', 'Новый заказ'), ('REP', 'Повтор заказа')], default='NEW', max_length=200, verbose_name='Тип заказа')),
                ('mask_name', models.CharField(max_length=200, null=True, verbose_name='Номер шаблона')),
                ('order_type', models.CharField(choices=[('MPW', 'MPW'), ('REP', 'Повтор'), ('ENG', 'Инженерный')], default='ENG', help_text='Пояснение для типа запуска', max_length=200, verbose_name='Тип запуска')),
                ('product_count', models.IntegerField(help_text='Количество уникальных структур в кадре', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Число проектов в кадре')),
                ('formation_frame_by_customer', models.BooleanField(default=False, help_text='Заказчик самостоятельно определяем расположение структур в кадре', verbose_name='Формирование кадра заказчиком')),
                ('substrate_type', models.CharField(choices=[('standard', 'Стандартная толщина подложки'), ('non_standard', 'Нестандартная толщина подложки')], default='standard', help_text='Пояснение для типа подложки', max_length=15, verbose_name='Тип толщины подложки')),
                ('dc_rf_probing_e_map', models.CharField(choices=[('DC Probing', 'DC проверка'), ('RF Probing', 'RF проверка'), ('No', 'Без проверки')], default='No', help_text='Будет ли проводиться зондовый контроль параметров на структурах, его тип', max_length=200, verbose_name='Контроль электрических параметров на пластине')),
                ('dc_rf_probing_inking', models.BooleanField(help_text='Маркировка баркованных структур по результатам зондового контроля', verbose_name='Маркировка брака по электрическим параметрам')),
                ('visual_inspection_inking', models.BooleanField(help_text='Визуальный контроль структур на пластине с последующей маркировкой бракованных', verbose_name='Визуальный контроль и маркировка брака')),
                ('experimental_structure', models.BooleanField(default=False, help_text='Запуск экспериментальных структур Потребителя,                                                         выходящих за рамки библиотеки стандартных элементов, без                                                         гарантии работоспособности таких структур.', verbose_name='Экспериментальная структура')),
                ('dicing_method', models.CharField(choices=[('DC', 'Дисковая резка'), ('LS', 'Лазер')], default='DC', max_length=200, verbose_name='Способ разделения пластины на кристаллы')),
                ('tape_uv_support', models.BooleanField(help_text='Засветка полимерного носителя, на который наклеена                                             пластина  для ослабления его клеющей способности для последующего                                             самостоятельного съёма структур силами потребителя', verbose_name='УФ засветка полимерного носителя')),
                ('wafer_deliver_format', models.CharField(choices=[('Пластины неразделенные', 'Пластины неразделенные'), ('Пластина разделенная на полимерном носителе', 'Пластина разделенная на полимерном носителе'), ('Кристаллы в таре', 'Кристаллы в таре')], default='Пластины неразделенные', help_text='Выбор вида разделения пластины на                                             отдельные структуры перед отгрузкой, либо его отсутсвие', max_length=200, verbose_name='Вид поставки пластин')),
                ('container_for_crystals', models.CharField(choices=[('Тара для пластин', 'Тара для пластин'), ('Пластмассовые ячейки', 'Пластмассовые ячейки'), ('Gel-Pak', 'Gel-Pak')], default='Gel-Pak', help_text='Выбор тары, в которой будут                                             поставляться структуры после разделения пластины', max_length=200, verbose_name='Вид тары для кристаллов')),
                ('parametric_monitor_control', models.BooleanField(default=False, verbose_name='Предоставление данных контроля параметрического монитора')),
                ('multiplan_dicing_plan', models.BooleanField(help_text='Потребитель сам определяет схему разделения                                                 пластины на структуры и предоставляет на фабрику', verbose_name='Разделение пластины на кристаллы по схеме заказчика')),
                ('multiplan_dicing_plan_file', models.FileField(blank=True, default='', null=True, upload_to='uploads/dicing_plan/%Y/%m/%d/', verbose_name='Файл ')),
                ('package_servce', models.BooleanField(help_text='Заказ сборки и корпусирования микросхем силами производителя', verbose_name='Корпусирование силами производителя')),
                ('delivery_premium_template', models.BooleanField(help_text='Запуск шаблонов вне общей очереди ', verbose_name='Ускоренный запуск производства фотошаблонов')),
                ('delivery_premium_plate', models.BooleanField(help_text='Запуск производстся пластин вне общей очереди', verbose_name='Ускоренный запуск производства пластин')),
                ('special_note', models.TextField(help_text=None, max_length=2000, null=True, verbose_name='Заметка')),
                ('order_date', models.DateTimeField(null=True, verbose_name='Дата оплаты')),
                ('deadline_date', models.DateTimeField(null=True, verbose_name='Срок выполнения по договору')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Заказ оплачен?')),
                ('contract_is_ready', models.BooleanField(default=False, verbose_name='Подписание договора')),
                ('order_status', models.CharField(choices=[('NFW', 'Необходима доработка'), ('OVK', 'На проверке'), ('OVC', 'На проверке'), ('OA', 'Принят'), ('SA', 'Подписание договора'), ('CSA', 'Подписание договора'), ('ESA', 'Подписание договора'), ('OGDS', 'Загрузка GDS'), ('CGDS', 'Загрузка GDS'), ('EGDS', 'Загрузка GDS'), ('PO', 'Оплата'), ('POK', 'Подтверждение оплаты'), ('POC', 'Подтверждение оплаты'), ('MPO', 'Производство'), ('SO', 'Отгрузка'), ('PS', 'Пластины отправлены'), ('CR', 'Подтверждение получения пластин'), ('EO', 'Завершен')], default='OVK', max_length=200, verbose_name='Статус заказа')),
                ('invoice_file', models.FileField(blank=True, default='', upload_to='uploads/invoices/%Y/%m/%d/', verbose_name='Файл счета')),
                ('contract_file', models.FileField(blank=True, default='', upload_to='uploads/contracts/%Y/%m/%d/', verbose_name='Файл договора')),
                ('GDS_file', models.FileField(blank=True, default='', upload_to='uploads/GDS/%Y/%m/%d/', verbose_name='Файл GDS')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('selected_diameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.diameter', verbose_name='Диаметр')),
                ('platform_code', models.ForeignKey(help_text='Предприятие, на котором будет запущено производство пластин', on_delete=django.db.models.deletion.CASCADE, to='account.platform', verbose_name='Площадка')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('technical_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.technicalprocess', verbose_name='Техпроцесс')),
                ('selected_thickness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.thickness', verbose_name='Толщина')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.order')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='account.topic'),
        ),
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_read_by', to='account.message')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
