# Generated by Django 4.1.13 on 2024-11-25 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=200, verbose_name='Название платформы')),
                ('platform_code', models.CharField(max_length=5, verbose_name='Код платформы')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_process', models.CharField(max_length=50, verbose_name='Название технического процесса')),
                ('PDK_file', models.FileField(blank=True, default='', upload_to='uploads/PDK/%Y/%m/%d/', verbose_name='Файл КИП')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Substrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thikness', models.IntegerField(null=True, verbose_name='Толщина подложки')),
                ('diameter', models.IntegerField(null=True, verbose_name='Диаметр подложки')),
                ('tech_proces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.technicalprocess')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('company_name', models.CharField(max_length=200, verbose_name='Наименование компании заказчика')),
                ('is_nda_signed', models.BooleanField(default=False, verbose_name='NDA подписано?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=14, verbose_name='Номер заказа')),
                ('customer_product_name', models.CharField(max_length=200, verbose_name='Имя запуска')),
                ('mask_name', models.CharField(max_length=200, null=True, verbose_name='Номер шаблона')),
                ('order_type', models.CharField(choices=[('MPW', 'MPW'), ('REP', 'Повтор'), ('ENG', 'Инженерный')], default='ENG', max_length=200, verbose_name='Тип запуска')),
                ('product_count', models.IntegerField(null=True, verbose_name='Число проектов в кадре')),
                ('dc_rf_probing_e_map', models.CharField(choices=[('DC Probing', 'DC проверка'), ('RF Probing', 'RF проверка'), ('No', 'Без проверки')], default='No', max_length=200, verbose_name='E-map проверка')),
                ('dc_rf_probing_inking', models.BooleanField(verbose_name='Inking проверка')),
                ('visual_inspection_inking', models.BooleanField(verbose_name='Визуальная проверка')),
                ('dicing_method', models.CharField(choices=[('SAW', 'Пила')], default='SAW', max_length=200, verbose_name='Метод резки')),
                ('tape_uv_support', models.BooleanField(verbose_name='УФ засветка')),
                ('wafer_deliver_format', models.CharField(choices=[('Пластина (без резки)', 'Пластина (без резки)'), ('Пластина резанная', 'Пластина резанная'), ('Гельпак', 'Гельпак')], default='Пластина (без резки)', max_length=200, verbose_name='Вариант упаковки')),
                ('multiplan_dicing_plan', models.BooleanField(verbose_name='Сложная резка')),
                ('package_servce', models.BooleanField(verbose_name='Корпусирование')),
                ('delivery_premium_template', models.BooleanField(verbose_name='Ускоренный запуск шаблона')),
                ('delivery_premium_plate', models.BooleanField(verbose_name='Ускоренный запуск пластины')),
                ('special_note', models.CharField(choices=[('Пластина (без резки)', 'Пластина (без резки)'), ('Пластина резанная', 'Пластина резанная'), ('Гельпак', 'Гельпак')], default='Пластина (без резки)', max_length=2000, verbose_name='Заметка')),
                ('order_date', models.DateTimeField(null=True, verbose_name='Дата заказа (оплаты)')),
                ('deadline_date', models.DateTimeField(null=True, verbose_name='Срок выполнения по договору')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Заказ оплачен?')),
                ('order_status', models.CharField(choices=[('NFW', 'Необходима доработка'), ('OVK', 'На проверке у куратора'), ('OVC', 'На проверке у исполнителя'), ('OA', 'Принят'), ('OGDS', 'Согласование'), ('PO', 'Оплата'), ('POK', 'Подтверждение оплаты куратором'), ('POC', 'Подтверждение оплаты исполнителем'), ('MPO', 'Производство'), ('SO', 'Отгрузка'), ('EO', 'Завершен')], default='OVK', max_length=200, verbose_name='Статус заказа')),
                ('invoice_file', models.FileField(blank=True, default='', upload_to='uploads/invoices/%Y/%m/%d/', verbose_name='Файл счета')),
                ('contract_file', models.FileField(blank=True, default='', upload_to='uploads/contracts/%Y/%m/%d/', verbose_name='Файл договора')),
                ('GDS_file', models.FileField(blank=True, default='', upload_to='uploads/GDS/%Y/%m/%d/', verbose_name='Файл GDS')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('platform_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.platform')),
                ('substrate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.substrate')),
                ('technical_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.technicalprocess')),
            ],
        ),
    ]
