# Generated by Django 4.1.13 on 2025-01-16 09:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='container_for_crystals',
            field=models.CharField(choices=[('Gel-Pak', 'Gel-Pak'), ('Пластмассовые ячейки', 'Пластмассовые ячейки'), ('Чашка Петри', 'Чашка Петри')], default='Gel-Pak', max_length=200, verbose_name='Вид тары для кристаллов'),
        ),
        migrations.AddField(
            model_name='order',
            name='experimental_structure',
            field=models.BooleanField(default=False, verbose_name='Экспериментальная структура'),
        ),
        migrations.AddField(
            model_name='order',
            name='formation_frame_by_customer',
            field=models.BooleanField(default=False, verbose_name='Формирование кадра заказчиком'),
        ),
        migrations.AddField(
            model_name='order',
            name='multiplan_dicing_plan_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='uploads/dicing_plan/%Y/%m/%d/', verbose_name='Файл '),
        ),
        migrations.AddField(
            model_name='order',
            name='parametric_monitor_control',
            field=models.BooleanField(default=False, verbose_name='Предоставление данных контроля параметрического монитора'),
        ),
        migrations.AddField(
            model_name='substrate',
            name='thikness_type',
            field=models.CharField(choices=[('standard', 'Стандартная толщина подложки'), ('non_standard', 'Нестандартная толщина подложки')], default='standard', max_length=15, verbose_name='Тип толщины'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dc_rf_probing_e_map',
            field=models.CharField(choices=[('DC Probing', 'DC проверка'), ('RF Probing', 'RF проверка'), ('No', 'Без проверки')], default='No', max_length=200, verbose_name='Контроль электрических параметров на пластине'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dc_rf_probing_inking',
            field=models.BooleanField(verbose_name='Маркировка брака по электрическим параметрам'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_premium_plate',
            field=models.BooleanField(verbose_name='Ускоренный запуск производства пластин'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_premium_template',
            field=models.BooleanField(verbose_name='Ускоренный запуск производства фотошаблонов'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dicing_method',
            field=models.CharField(choices=[('SAW', 'Пила')], default='SAW', max_length=200, verbose_name='Способ разделения пластины на кристаллы'),
        ),
        migrations.AlterField(
            model_name='order',
            name='multiplan_dicing_plan',
            field=models.BooleanField(verbose_name='Разделение пластины на кристаллы по схеме заказчика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='package_servce',
            field=models.BooleanField(verbose_name='Корпусирование силами производителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='platform_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.platform', verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_count',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Число проектов в кадре'),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_note',
            field=models.CharField(choices=[('Пластины неразделенные', 'Пластины неразделенные'), ('Пластина разделенная на полимерном носителе', 'Пластина разделенная на полимерном носителе'), ('Кристаллы в таре', 'Кристаллы в таре')], default='Пластины неразделенные', max_length=2000, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tape_uv_support',
            field=models.BooleanField(verbose_name='УФ засветка полимерного носителя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='technical_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.technicalprocess', verbose_name='Техпроцесс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='visual_inspection_inking',
            field=models.BooleanField(verbose_name='Визуальный контроль и маркировка брака'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wafer_deliver_format',
            field=models.CharField(choices=[('Пластины неразделенные', 'Пластины неразделенные'), ('Пластина разделенная на полимерном носителе', 'Пластина разделенная на полимерном носителе'), ('Кристаллы в таре', 'Кристаллы в таре')], default='Пластины неразделенные', max_length=200, verbose_name='Вид поставки пластин'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.order')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='account.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='topic_files/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='account.message')),
            ],
        ),
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
