# Generated by Django 4.1.13 on 2024-11-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_technicalprocess_pdk_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalprocess',
            name='PDK_file',
            field=models.FileField(blank=True, default='', upload_to='uploads/PDK/2024/%Y/%m/%d/', verbose_name='Файл КИП'),
        ),
    ]
